name: incrementDevBranch

on:

  


  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'
        cache: maven
    - name: Java and Maven Version
      
      
      run: java -version && mvn -v
    - name: Build with Maven
      
      
      run: mvn -B package --file pom.xml
    - name: Verify Branch That Triggered Workflow
      run: echo "Brach running this action is $GITHUB_REF"

  
